name: 'Bug Report'
description: 'Report an issue or regression with Torii USB'
labels: [
  'pending-verification'
]

body:
  - type: markdown
    attributes:
      value: '## Report a bug with Torii USB'
  - type: markdown
    attributes:
      value: >
        Thank you for helping make Torii USB better for everyone!


        Please fill out the form below as best you can, and we will
        review it and get back to you as soon as we can.


        Also, make sure to review the [Contribution Guidelines](https://github.com/shrine-maiden-heavy-industries/torii-usb/blob/main/CONTRIBUTING.md#reporting-issues).

  - type: input
    id: torii-version
    attributes:
      label: 'Torii Version'
      description: >
        The version of Torii this bug was encountered on.


        If using the development branch, then you can use the following command to get
        the specific version you're on:


        `python -c 'import torii;print(torii.__version__)'`
      placeholder: 'e.g. v1.0.5'
    validations:
      required: true

  - type: input
    id: torii-usb-version
    attributes:
      label: 'Torii USB Version'
      description: >
        The version of Torii USB this bug was encountered on.


        If using the development branch, then you can use the following command to get
        the specific version you're on:


        `python -c 'import torii_usb;print(torii_usb.__version__)'`
      placeholder: 'e.g. v1.0.5'
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: 'Python Version'
      description: >
        Which versions of Python does this occur on?


        If it happens on more than one version, select all applicable.
      options:
        - 'CPython 3.11'
        - 'CPython 3.12'
        - 'CPython 3.13'
        - 'CPython 3.14'
        - 'PyPy 3.11'
        - 'Other'
      multiple: true
    validations:
      required: true

  - type: input
    id: python-version-other
    attributes:
      label: 'Other Python Version'
      description: >
        If you selected `Other` in the dropdown above, specify the Python implementation and version
        here.
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: 'Operating System'
      description: >
        If the problem occurs on one or more specific operating systems select all as appropriate.


        Please note, we have limited testing on less common systems such as things like Plan9, Haiku,
        illumos-based systems, or most BSDs, so an issue occurring on one of those platforms will take
        longer to diagnose.
      options:
        - 'Linux'
        - 'BSD'
        - 'illumos'
        - 'Solaris'
        - 'macOS'
        - 'Windows'
        - 'Other'
      multiple: true
    validations:
      required: false

  - type: input
    id: platform-version
    attributes:
      label: 'Operating System Version'
      description: >
        The specific release and/or version of the Operating System specified.


        If more than one operating system and/or version, please list them all separated
        by a comma.
      placeholder: 'e.g. Arch Linux, OpenIndiana Hipster 2025.04, OpenBSD 7.7'
    validations:
      required: false

  - type: markdown
    attributes:
      value: '### A Note on Reproducibility'
  - type: markdown
    attributes:
      value: >
        When providing steps to reproduce the issue, please ensure that the issue
        is reproducible in the latest development revision of Torii USB. Also, ensure to
        provide all necessary source files needed if possible.


        Please see [https://stackoverflow.com/help/mcve](https://stackoverflow.com/help/mcve)
        for information on how to create a Minimal, Complete, and Verifiable Example
        (MCVE).


        However, we know this is not always possible, and things can be hard to minify, so if you
        cant fully that is fine, it just might take a bit longer to diagnose the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: 'What happened?'
      description: >
        Please provide as detailed of a description as you can, and any additional steps needed to
        reproduce it if possible.
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: 'Code of Conduct'
      description: >
        By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/shrine-maiden-heavy-industries/torii-usb/blob/main/CODE_OF_CONDUCT.md)
        and [AI usage Policy](https://github.com/shrine-maiden-heavy-industries/torii-usb/blob/main/CONTRIBUTING.md#ai-usage-policy).
      options:
        - label: 'I agree to follow the Torii USB Code of Conduct and AI Usage Policy'
          required: true
