blank_issues_enabled: false
contact_links:
  - name: 'View The Documentation'
    url: 'https://torii-usb.shmdn.link/'
    about: 'Read the Torii USB documentation.'
  - name: 'Start A Discussion'
    url: 'https://github.com/shrine-maiden-heavy-industries/torii-usb/discussions'
    about: 'Have a question? Got something cool to share? Do it here!'
  - name: 'Chat with Us'
    url: 'https://web.libera.chat/#torii'
    about: 'Join us on IRC for development discussion or just to hang out and ask questions'
