name: Feature Request
description: "Submit a feature request for SOL"
labels: ["feature-request"]
body:
  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: "A clear and detailed description of the feature."
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/shrine-maiden-heavy-industries/usb-construct/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
