name: "SOL Docs"
on:
  push:
    branches:
      - 'main'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Initialize Env
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        shell: bash
        run: |
          sudo apt-get update
          python -m pip install --user --upgrade pip setuptools wheel setuptools_scm nox

      - name: Build Docs
        shell: bash
        run: |
          nox -s docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: build/docs/
          CLEAN: true
