name: "SOL PR Tests"
on:
  pull_request: {}

jobs:
  test-torii:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12-dev', 'pypy-3.9-v7.3.11']
      fail-fast: true

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Initialize Env
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup OSS CAD Suite
        uses: YosysHQ/setup-oss-cad-suite@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup
        shell: bash
        run: |
          python -m pip install --user --upgrade pip setuptools wheel setuptools_scm nox


      - name: Run Style Check
        shell: bash
        run: |
          nox -s lint

      - name: Run Tests
        shell: bash
        run: |
          nox -s test
      - name: Codecov
        if: success() && github.repository == 'shrine-maiden-heavy-industries/sol'
        uses: codecov/codecov-action@v3
