name: "SOL PR Tests"
on:
  pull_request: {}

jobs:
  test-torii:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', 'pypy3.10-v7.3.15']
      fail-fast: true

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Initialize Env
        shell: bash
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo "$HOME/.local/bin:$PATH" >> $GITHUB_PATH
          echo "GITHUB_WORKSPACE=\"`pwd`\"" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OSS CAD Suite
        uses: YosysHQ/setup-oss-cad-suite@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup
        shell: bash
        run: |
          python -m pip install --user --upgrade pip setuptools wheel setuptools_scm nox


      - name: Run Style Check
        shell: bash
        run: |
          nox -s lint

      - name: Run Tests
        shell: bash
        run: |
          nox -s test
      - name: Codecov
        if: success() && github.repository == 'shrine-maiden-heavy-industries/sol'
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          files: ./build/tests/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
